version: "3"

services:
  node:
    image: node:16
    container_name: psel_xp
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db

  db:
    container_name: psel_xp_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: psel_xp_net
